name: Test changes
on:
  push:
    branches-ignore:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  MONGOMS_VERSION: 7.0.0
  MONGOMS_DOWNLOAD_URL: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-7.0.0.tgz
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      package_version: ${{ steps.get_version.outputs.package_version }}
    permissions:
      contents: read
    steps:
    # cache download ./node_modules/.cache
      - uses: actions/checkout@v3 
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      # - run: npm ci
      # - run: npm run test
      - run: |
           echo ${{ runner.os }}